# .github/workflows/build.yml
name: Build and Upload Code

on:
  workflow_call:
    inputs:
      zip-dir:
        description: "Directory to zip"
        required: true
        type: string
      artifact-path:
        description: "Path to save the zip file"
        required: true
        type: string
      artifact-name:
        description: "Name for the uploaded artifact"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify build directory exists
        run: |
          if [ ! -d "${{ inputs.zip-dir }}" ]; then
            echo "Error: Directory ${{ inputs.zip-dir }} does not exist."
            exit 1
          fi

      - name: Create ZIP file
        run: zip -r ${{ inputs.artifact-path }} ${{ inputs.zip-dir }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
