name: Validate and Build Workflow

on:
  push:
    branches:
      - main 

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      zip-dir: my-code        
      artifact-path: my-code.zip
      artifact-name: my-code-artifact

  deploy:
    needs: build  
    uses: ./.github/workflows/deploy.yml
    with:
      azure_webapp_name: my-webapp-108
      package_path: my-code.zip
      slot_name: staging
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}


  swap:
    needs: deploy 
    uses: ./.github/workflows/swap-slot.yml 
    with:
      azure_webapp_name: my-webapp-108
      resource_group: my-rsg
      source_slot_name: staging
      target_slot_name: production