name: Validate and Build Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      zip-dir: my-code         # Folder in your repo to be zipped
      artifact-path: my-code.zip
      artifact-name: my-code-artifact
