name: Validate and Build Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      zip-dir: my-code         # Folder in your repo to be zipped
      artifact-path: my-code.zip
      artifact-name: my-code-artifact

  deploy:
    needs: build  # Ensure deploy job runs only after the build job succeeds
    uses: ./.github/workflows/deploy.yml
    with:
      azure_webapp_name: my-webapp-108
      package_path: my-code.zip
      slot_name: staging
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}


  swap:
    needs: deploy
    uses: ./.github/workflows/swap-slots.yml  
    with:
      azure_webapp_name: ${{ secrets.AZURE_APP_NAME }}  
      publish_profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
      source_slot: staging   
      target_slot: production 
