name: Swap Deployment Slots

on:
  workflow_call:
    inputs:
      azure_webapp_name:
        description: "Name of the Azure Web App"
        required: true
        type: string
      resource_group:
        description: "Resource group name for the Azure Web App"
        required: true
        type: string
      source_slot_name:
        description: "Source slot name (e.g., staging)"
        required: true
        type: string
      target_slot_name:
        description: "Target slot name (e.g., production)"
        required: true
        type: string
    secrets:
      AZURE_PUBLISH_PROFILE_1:
        description: "Azure publish profile for deployment"
        required: true

jobs:
  swap:
    runs-on: ubuntu-latest

    steps: 
      - name: Login to Azure using Publish Profile
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_1 }}
      

      - name: Swap Deployment Slots
        run: |
          az webapp deployment slot swap \
            --name ${{ inputs.azure_webapp_name }} \
            --resource-group ${{ inputs.resource_group }} \
            --slot ${{ inputs.source_slot_name }} \
            --target-slot ${{ inputs.target_slot_name }}
